spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
google.client-id=450998180907-r7r2loc02s1gghfmf76tgtc0lnkdpcog.apps.googleusercontent.com

spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.data-source-properties.prepareThreshold=0
# デフォルト(30分)から10分に短縮し、DB側より先にアプリ側から接続を張り替えさせる
spring.datasource.hikari.max-lifetime=600000
# 接続が生きているか定期的にチェックする（オプション）
spring.datasource.hikari.keepalive-time=30000

server.port=${PORT:8080}