spring.datasource.url=jdbc:postgresql://db.fobryznkldobyyivwkcx.supabase.co:5432/postgres?ssl=true&sslmode=require&preferQueryMode=simple

spring.datasource.username=postgres
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=1

server.port=${PORT:8080}