spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.fobryznkldobyyivwkcx
spring.datasource.password=kazuyaogawa20031112
spring.datasource.driver-class-name=org.postgresql.Driver
google.client-id=450998180907-r7r2loc02s1gghfmf76tgtc0lnkdpcog.apps.googleusercontent.com
logging.level.org.springframework.security=DEBUG
jwt.secret=my-super-secret-key-my-super-secret-key