spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
google.client-id=450998180907-r7r2loc02s1gghfmf76tgtc0lnkdpcog.apps.googleusercontent.com

spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.data-source-properties.prepareThreshold=0
jwt.secret=${JWT_SECRET}

server.port=${PORT:8080}